using Catan.models;
namespace Catan.DTO;
public record JoinRequestDto(int UserId, int TeamId);
public record AuthRequestDto(string Username, string Password);
public record CreateTeamRequestDto(int UserId, string Name);
public record CreateGameRequestDto(int UserId, int TeamId, GameSettings Settings);
public record GameHistoryDto(int GameCount, IEnumerable<GameListDto> GameList);
public record GameListDto(DateTime Date, string Name, int Id);
public record UpdateRelationsRequestDto(int PlayerId, int NewValue);
public record UpdateResourceRequestDto(string Resource, int Amount);
public record RenameRequestDto(string Name);